esphome:
  name: led-stairs
  friendly_name: Light Stairs LED

esp8266:
  board: esp8285

external_components:
  - source: github://YOUR_GITHUB_USER/esphome-sonoff-l1@main
    components: [sonoff_l1]

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_enc_key

ota:
  platform: esphome
  password: !secret ota_pwd

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password
  ap:
    ssid: "Stairs LED Fallback Hotspot"
    password: !secret ap_pwd

captive_portal:

light:
  - platform: sonoff_l1
    id: led_output
    name: "Staircase"
    effects:
      - lambda:
          name: Colorful Gradient (Smooth)
          lambda: |-
            id(led_output).setModeGradient();
      - lambda:
          name: Colorful Breath (Fade)
          lambda: |-
            id(led_output).setModeBreath();
      - lambda:
          name: RGB Gradient
          lambda: |-
            id(led_output).setModeRGBGradient();
      - lambda:
          name: RGB Pulse (Strobe)
          lambda: |-
            id(led_output).setModeRGBPulse();
      - lambda:
          name: RGB Breath
          lambda: |-
            id(led_output).setModeRGBBreath();
      - lambda:
          name: RGB Strobe (Flash)
          lambda: |-
            id(led_output).setModeRGBStrobe();
      - lambda:
          name: Sound Reactive
          lambda: |-
            id(led_output).setModeSync();
