substitutions:
  device_name: sonoff-l1-device            # CHANGE THIS (lowercase, no spaces)
  friendly_name: "Sonoff L1 Device"        # CHANGE THIS (can have spaces)
esphome:                                   # Remeber to also change the passwords and keys below
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp8285

external_components:
  - source: github://ettiennecoetzee/esphome-sonoff-l1@main
    components: [sonoff_l1]

logger:
  baud_rate: 0

api:
  encryption:
    key: "YOURSECRETAPIKEY"            #change this

ota:
  platform: esphome
  password: "YOURSECRETOTAPASSWORD"    #change this

wifi:
  networks:
    - ssid: !secret wifi_ssid       #or add your wifi details here
      password: !secret wifi_password

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "YOURPASSWORDFORTHEHOTSPOT"    #change this

captive_portal:

light:
  - platform: sonoff_l1
    id: l1
    name: "${friendly_name}"
    effects:
      - lambda:
          name: Colorful Gradient (Smooth)
          lambda: |-
            id(l1).setModeGradient();
      - lambda:
          name: Colorful Breath (Fade)
          lambda: |-
            id(l1).setModeBreath();
      - lambda:
          name: RGB Gradient
          lambda: |-
            id(l1).setModeRGBGradient();
      - lambda:
          name: RGB Pulse (Strobe)
          lambda: |-
            id(l1).setModeRGBPulse();
      - lambda:
          name: RGB Breath
          lambda: |-
            id(l1).setModeRGBBreath();
      - lambda:
          name: RGB Strobe (Flash)
          lambda: |-
            id(l1).setModeRGBStrobe();
      - lambda:
          name: Sound Reactive
          lambda: |-
            id(l1).setModeSync();
