esphome:
  name: tv-led-strip
  friendly_name: Light LED TV Strip

esp8266:
  board: esp8285

external_components:
  - source: github://YOUR_GITHUB_USER/esphome-sonoff-l1@main
    components: [sonoff_l1]

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_enc_key

ota:
  platform: esphome
  password: !secret ota_pwd

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password
  ap:
    ssid: "Tv-Led-Strip Fallback Hotspot"
    password: !secret ap_pwd

captive_portal:

light:
  - platform: sonoff_l1
    id: tv_backlight
    name: "TV Backlight"
    effects:
      - lambda:
          name: Colorful Gradient (Smooth)
          lambda: |-
            id(tv_backlight).setModeGradient();
      - lambda:
          name: Colorful Breath (Fade)
          lambda: |-
            id(tv_backlight).setModeBreath();
      - lambda:
          name: RGB Gradient
          lambda: |-
            id(tv_backlight).setModeRGBGradient();
      - lambda:
          name: RGB Pulse (Strobe)
          lambda: |-
            id(tv_backlight).setModeRGBPulse();
      - lambda:
          name: RGB Breath
          lambda: |-
            id(tv_backlight).setModeRGBBreath();
      - lambda:
          name: RGB Strobe (Flash)
          lambda: |-
            id(tv_backlight).setModeRGBStrobe();
      - lambda:
          name: Sound Reactive
          lambda: |-
            id(tv_backlight).setModeSync();
